### ISSUE TITLE
Add interim query results into transactions

### ISSUE THREAD

**Issue by jeremydaly** [jeremydaly/serverless-mysql#1]
Dominggus Salampesy point out a use case that is not currently supported. For example, if you wanted to get interim results *within* a transaction:

```javascript
beginTransaction()
.then(() => executeQuery(‘INSERT INTO table (foo) VALUES(?)’, [1])
.then((r) => {
console.log(r.insertId);
return executeQuery(‘INSERT INTO table2 (bar), [r.insertId])
});
```

Serverless MySQL is queuing queries and then waiting for the `commit()` method to be called before executing any of them. I'll have to think about the best way to provided query results to successive queries. Maybe simply passing the `results` array in to each subsequent query call and providing a `tap()` method to review the results.

**Comment by domingguss** [comment]
great!
