### ISSUE TITLE
How to execute some code during a transaction?

### ISSUE THREAD

**Issue by JakubMatejka** [jeremydaly/serverless-mysql#11]
I would like to use this library in our project but it uses some more complex logic during a transaction. E.g. it selects a row but when the row does not exist, an exception is thrown. Only if the row exists, the script continues with other queries. Using (promisifed) mysql module it looks like this:
```javascript
await this.db.beginTransactionAsync();
const app = await this.db.queryAsync('SELECT * FROM appVersions WHERE id = ? ORDER BY version DESC LIMIT 1', [id]);
if (!_.size(app)) {
  throw this.err(404, `App ${id} does not exist`);
}
// Update the `app` object a little bit more, e.g. increase version number
await this.db.queryAsync('INSERT INTO appVersions SET ?', app);
await this.db.commitAsync();
```

But I don't see how to do something like this using your syntax (`db.commit().query().commit()`). Is it possible?

**Comment by jeremydaly** [comment]
Hi @JakubMatejka,

You can execute code within a chained `.query()` call by using a function as the argument instead of a standard query. See here: https://github.com/jeremydaly/serverless-mysql#transaction-support

Your code above should be able to be written like this:

```javascript
let result = await mysql.transaction()
  .query('SELECT * FROM appVersions WHERE id = ? ORDER BY version DESC LIMIT 1', [id])
  .query(app => {
     if (app.length === 0) {
       throw this.err(404, `App ${id} does not exist`);
     }
    // Update the `app` object a little bit more, e.g. increase version number
    return ['INSERT INTO appVersions SET ?', app]
  )
  .commit()
``` 

You could also add a `.rollback()` if you wanted to detect general errors as well.

**Comment by JakubMatejka** [comment]
Thanks @jeremydaly that's great! I've noticed the second query (`.query((r) => ['UPDATE table SET x = 1 WHERE id = ?', r.insertId])`) but I haven't realized I can put a function there.

**Comment by JakubMatejka** [comment]
Just maybe a second question. ;o) Sometimes we reuse a subquery by calling a function like this:
```javascript
await this.db.beginTransactionAsync();
const app = await this.getAppLastVersion(id);
await this.addAppVersion(app, paramsOut, userEmail);
await this.db.commitAsync();
```

and 

```javascript
  async getAppLastVersion(id) {
    const app = await this.db.queryAsync('SELECT * FROM appVersions WHERE id = ? ORDER BY version DESC LIMIT 1', [id]);
    if (!_.size(app)) {
      throw this.err(404, `App ${id} does not exist`);
    }
    return app[0];
  }
```

Such approach is possible? Just now I'm not sure if calling another query in the function body of `.query(() => {})` is rational.

**Comment by jeremydaly** [comment]
Hmm, probably possible if you add `async` to the function handler, e.g. `.query(async app => { ... })`, but might be easier to just put that query and logic in another `.query()` call.

Also, a function in `.query()` actually receives TWO arguments. The first is the result of the previous query, the second is an array that stores the results of **ALL** queries in the transaction. Useful if you need access to a query result from several calls ago.
