### ISSUE TITLE
Frequent random ECONNRESET error across all functions using serverless-mysql

### ISSUE THREAD

**Issue by zaros** [jeremydaly/serverless-mysql#110]
Node version: 14
DB: 5.7.mysql_aurora.2.10.0

At some point a few weeks ago, my application which has a few dozen functions using serverless-mysql started having "read ECONNRESET" errors for no apparent reason. 

<img width="421" alt="Screenshot 2021-06-25 at 12 29 43 PM" src="https://user-images.githubusercontent.com/738805/123370036-77287580-d5b1-11eb-96f8-1e3a60edd72d.png">

But I can't reproduce it; e.g. when I test a Lambda and kill the connection directly from my MySQL client, the Lambda just reconnects normally as expected.

I suspect the error is the TLS negotiation of NodeJS, not in serverless-mysql, but I'm looking for a solution to handle the error other than wrapping every query in a catch and retry (this would definitely get around it, but it's a lot of rework)

Has anyone encountered this issue?  How could I setup serverless-mysql to handle this error and retry the connection or query gracefully?

**Comment by zaros** [comment]
I have solved the issue by switching to Aurora Serverless -- this is after determining that the ECONNRESET errors only started after changing my previous RDS Aurora instance from t3 to r6g type. As a complication, we were also upgrading to Node 14 at this time so it was hard figure out if the error is caused by RDS or Node14. 

Also, as an earlier workaround I've also implemented retry with exponential backoff for all queries. This approach does work because the error is random and almost never repeats on retry. 

But it is clear after changing to Aurora Serverless the  errors disappeared and the retry code I implemented never trigger anymore.

**Comment by pianomansam** [comment]
> Also, as an earlier workaround I've also implemented retry with exponential backoff for all queries. This approach does work because the error is random and almost never repeats on retry.

@zaros could you link to this earlier work? I'm experiencing this same thing and would like to see if I could avoid the move to Aurora Serverless.

**Comment by zaros** [comment]
Hi @pianomansam  my projects are in a private repo, so here's a snippet of the code I use. 

```js

const MAX_RETRIES = 3; // we use an env variable in real code

//  a generic query
module.exports.getUser = async function (userId) {

    const result = await queryWithRetry({
        sql: `SELECT *
                  FROM users
                  WHERE
                      id = ?
                  LIMIT 1;`,
        values: [userId]
    });
   
    return result[0] ?? null;
}

async function queryWithRetry(query) {
    let result = null;
    const delayMs = 100; 
    let retries = 0;
    while (true) {
        try {
            await initDb();     // this func initialises the db conn if it doesn't exist yet
            result = await db.query(query);
            await db.end();
        } catch (err) {
            result = null;
            if (retries >= MAX_RETRIES || !err['message'].includes('ECONNRESET')) {    
                throw err;
            }
        }
        if (result != null) {
            break;
        }
        retries++;
        await new Promise(resolve => setTimeout(resolve, delayMs * retries));
    }

    return result;
}
```
