### ISSUE TITLE
Support for connection string

### ISSUE THREAD

**Issue by tonb** [jeremydaly/serverless-mysql#115]
It would be great if the library would support connection strings, e.g.:

```
import mysql from 'serverless-mysql';
const db = mysql('mysql://user:pass@host:port/database');
```

Or am I missing something, and is this already somehow possible?

**Comment by rawnly** [comment]
any news on this?

**Comment by naorpeled** [comment]
Hey @tonb and @Rawnly,
this was added in v1.5.5 🙏
