### ISSUE TITLE
SQLite

### ISSUE THREAD

**Issue by VndrGrhrd** [jeremydaly/serverless-mysql#121]
HI can I use with SQLite?

**Comment by naorpeled** [comment]
Hey @VndrGrhrd,
thanks for opening this issue and sorry for the huge delay.

You can specify a custom library in the configuration of the serverless-mysql instance.
If there's a sqlite library that implements exactly the same methods (we specifically use `createConnection`, `escape`, `escapeId` and `format`) it should theoretically work afaik,  not 100% sure about the queries syntax though, I haven't worked with SQLite in a while.

I'll be closing this but if you have any further questions feel free to ping me 🙏
