### ISSUE TITLE
TINYINT to BOOLEAN

### ISSUE THREAD

**Issue by pergunt** [jeremydaly/serverless-mysql#130]
Is there a way to transfrom `TINYINT` fields to `BOOLEAN` "on fly" where we are querring `TINYINT` fields? So intstead of returning `1 or 0 `we will be returning `true / false`

**Comment by naorpeled** [comment]
Hey @pergunt,
yes!

I recommend reading [this article](https://bobcares.com/blog/convert-tinyint-to-boolean-mysql/) that discusses this exact situation with several solutions for doing so.
