### ISSUE TITLE
How to get a single query result? Not an array.

### ISSUE THREAD

**Issue by Nhahan** [jeremydaly/serverless-mysql#131]
`SELECT * FROM orders WHERE id = ${id}`
I expected to get a single  object result but it returns an array.

How to control whether to receive query results in an array or not? 

Thank you for your help.

**Comment by naorpeled** [comment]
Hey @Nhahan,
we don't really deal with the content of the query in the scope of this library, 
so we can't really differentiate between a single result query and a multiple result query.

For such a thing I'd suggest using some kind of query builder,
such as Kysely.

I'll be closing this issue but feel free to ping me if you need anything :)
