### ISSUE TITLE
is this no longer being maintained? [High Level Threat]

### ISSUE THREAD

**Issue by tistisman** [jeremydaly/serverless-mysql#138]
This has a High Level Threat Security as this is still using Old MySQL Package

**Comment by trasherdk** [comment]
```js
const mysql = require('serverless-mysql')({
    library: require('mysql2'),
});
```

**Comment by naorpeled** [comment]
Hey @tistisman,
first of all thanks for opening this issue.

This library is being maintained 🙏 
Planning on updating the lib to mysql2 soon.
Will be closing this issue for now.

Feel free to ping me if you have any additional questions
