### ISSUE TITLE
Will this work with mysql2?

### ISSUE THREAD

**Issue by dev-embedthis** [jeremydaly/serverless-mysql#14]
Mysql2 has support for prepared statements. It is highly compatible. Has this module been tested with mysql2?

**Comment by jeremydaly** [comment]
No, this module is not tested with mysql2, but I'd be happy to accept PRs if you want to give it a try.

**Comment by navigiljshuusko** [comment]
Hi,

I'm sorry I'm not too familiar with PRs and don't know if mysql2 should be a separate version of this library, but I did some testing and did not find too many difficulties. 

I wanted to use `execute`, `namedPlaceholders` and the` IAM login` with mysql2. I have not yet done very much of testing but these seem to work fine.

Here is what I did.

1. Start with mysql2 
`const MYSQL = require('mysql2'); // MySQL2`

2. Add Execute function
const execute = async function(...args) {
	// Establish connection
	await connect();

	// Run the execute
	return new Promise((resolve, reject) => {
		if (client !== null) {
			client.execute(...args, async (err, results) => {
				if (err && err.code === 'PROTOCOL_SEQUENCE_TIMEOUT') {
					client.destroy(); // destroy connection on timeout
					resetClient(); // reset the client
					reject(err); // reject the promise with the error
				} else if (err && /^PROTOCOL_ENQUEUE_AFTER_/.test(err.code)) {
					resetClient(); // reset the client
					return resolve(execute(...args)); // attempt the query again
				} else if (err) {
					if (this && this.rollback) {
						await execute('ROLLBACK');
						this.rollback(err);
					}
					reject(err);
				}
				return resolve(results);
			});
		}
	});
}; // end execute

3. Return execute function
`return {
		connect,
		config,
		query,
		execute,
		end,
		quit,
		transaction,
		getCounter,
		getClient,
		getConfig,
		getErrorCount,
	};`

4. I added namedPlaceholders=true to library as default

`			client = MYSQL.createConnection(_cfg);
			client.config.namedPlaceholders = true;
`

5. Connecting with IAM account

signer.getAuthToken(
	{
		// uses the IAM role access keys to create an authentication token
		region,
		hostname: dbEndpoint,
		port: dbPort,
		username: dbUsername,
	},
	(err, token) => {
		if (err) {
			console.log(`could not get auth token: ${err}`);
			return err;
		}
		// console.log(token);
		connection = require('./serverless-mysql')({
			config: {
				host: dbEndpoint,
				port: dbPort,
				user: dbUsername,
				password: token,
				database: dbName,
				ssl: 'Amazon RDS',
				authSwitchHandler(data, cb2) {
					// modifies the authentication handler.
					if (data.pluginName === 'mysql_clear_password') {
						// authentication token is sent in clear text but connection uses SSL encryption
						cb2(null, Buffer.from(`${token}\0`));
					}
				},
			},
		});
	}
);

**Comment by jeremydaly** [comment]
You can now specify your MySQL library. I'm not sure how well transactions are handled, but basic connect and query functionality should work.

**Comment by powermikee** [comment]
Connection works. Query works but executing prepared statements does not.

Tried accessing the client directly:

const connection = mysql.getClient();
const [rows] = await connection.execute('SELECT * FROM users');

But connection comes through as null.

Any suggestions?

**Comment by yocmen** [comment]
this is how you make it work with mysql2

```javascript
  await mysql.connect();
  const conn = mysql.getClient();

  const [rows] = await conn
    .promise()
    .execute(Query, [userId, offset, length]);

  // Run clean up function
  await mysql.end();

  return rows;
```
