### ISSUE TITLE
Multiple transactions and passing of variables in-between queries

### ISSUE THREAD

**Issue by dmontecillo** [jeremydaly/serverless-mysql#141]
I have a code similar to the below, but I can't seem to understand how to do it using this library.

db.transaction().query('INSERT INTO TABLE1 (name,fname) VALUES (?, ?)')
.query((result) => {
    return [result.insertId, ['INSERT INTO TABLE2 (t1_id , amount) VALUES (? , ?)']];
})
.query(([t1.id, t2.id])=> {
 // Here lies the problem i cant seem to get the t1.id and t2.id simulataneously?
})

.commit()
.rollback(e => console.log('E: ', e))

Thanks

**Comment by naorpeled** [comment]
Hey @dmontecillo,
thanks for opening this issue.

I'll be investigating this for you.
Will keep you updated 🙏

**Comment by naorpeled** [comment]
Hey @dmontecillo,
you should be able to make a variable that stores the results of each step and then use it in the next parts of the chain.

Am I missing something? 🙏

**Comment by naorpeled** [comment]
Closing this due it being stale.
@dmontecillo feel free to ping me if you need anything.
