### ISSUE TITLE
Is consistency guaranteed if the MySQL DB is updated at the same time?

### ISSUE THREAD

**Issue by Arimuuuura** [jeremydaly/serverless-mysql#145]
Hi Jeremy,
Thank you for providing this excellent module. Now, I am using this module in AWS Lambda, and I have a question. If multiple users attempt to update or retrieve data from the same table simultaneously, is data consistency guaranteed? I understand that transactions allow for consistent processing.

**Comment by Arimuuuura** [comment]
Is it possible to write something like table lock for example?

**Comment by naorpeled** [comment]
Hey @Arimuuuura,
table locks allow you to achieve such functionality.
You could do something like

```typescript
conn.query('LOCK TABLE t WRITE')

// do some stuff
// .....

conn.query('UNLOCK TABLES')
```


I recommend reading the [MySQL docs](https://dev.mysql.com/doc/refman/8.0/en/lock-tables.html) to fully understand the benefits/limitations of this.


I'll be closing this issue,
but feel free to ping me if you need anything 🙏
