### ISSUE TITLE
Multi-database Connectivity

### ISSUE THREAD

**Issue by adevbuildingstuff** [jeremydaly/serverless-mysql#15]
I have a scenario where in my Lambda I need to connect to and run queries against two databases on two separate database servers. Is it possible to achieve this using your module? Here is my sample code:

```javascript
const config1 = {
	host: process.env.DB_HOST,
	user: process.env.DB_USER,
	password: process.env.DB_PASSWORD,
	database: process.env.DB_NAME
};

const config2 = {
	host: process.env.DB2_HOST,
	user: process.env.DB2_USER,
	password: process.env.DB2_PASSWORD,
	database: process.env.DB2_NAME
};

const mysql = require('serverless-mysql')();

exports.handler = async (event, context) => {
	context.callbackWaitsForEmptyEventLoop = false;

	try {
		mysql.config(config1);
		let results = await mysql.query('select * from email');
		console.log(results);
		
		mysql.config(config2);
		results = await mysql.query('select * from user_roles');
		console.log(results);
	} catch (error) {
		console.log(error);
	}
};
```

Note that the first console.log call correctly output the rows from the email table in the DB that config1 refers to. However, after changing the DB config to config2 and attempting the 2nd query, I get an error that indicates that the module tried to select from a user_roles table in the DB pointed to by config1 instead of selecting from config2's DB. So it appears then that your module can only support connecting to a single MySQL instance. Is that the case?

**Comment by tobilg** [comment]
I guess

```javascript
const mysql1 = require('serverless-mysql')();
const mysql2 = require('serverless-mysql')();

exports.handler = async (event, context) => {
	context.callbackWaitsForEmptyEventLoop = false;

	try {
		mysql1.config(config1);
		let results = await mysql1.query('select * from email');
		console.log(results);
		
		mysql2.config(config2);
		results = await mysql2.query('select * from user_roles');
		console.log(results);
	} catch (error) {
		console.log(error);
	}
};
```

could work?

**Comment by jeremydaly** [comment]
Sorry for the late replies. Yes, @tobilg suggesting would work. Each separate instance would manage its own connections.

**Comment by adevbuildingstuff** [comment]
Hi guys thanks for the responses, I'll test out the suggestion from @tobilg and see if it works.

**Comment by liam-betsworth** [comment]
I ran into this issue pretty early on as we're using multiple databases. I tried the solution mentioned by @tobilg but had no success.

The best way I've found to deal with this so far is to leave the database out of the config. Instead, include the database name in the query. For example:

```javascript
const mysql = require('serverless-mysql')();

exports.handler = async (event, context) => {
	context.callbackWaitsForEmptyEventLoop = false;

        const db1 = 'a_database';
        const db2 = 'another_database';

	try {
		mysql1.config(config1);
		let results = await mysql.query(`select * from ${db1}.email`);
		console.log(results);
		
		results = await mysql.query(`select * from ${db2}.user_roles`);
		console.log(results);
	} catch (error) {
		console.log(error);
	}
};
```

This seems to work pretty well, so long as you don't need to change host.

**Comment by petehanson** [comment]
I ran into this issue as well when trying to create two separate connections to different databases hosts/databases.  Submitted a PR that may solve it.

**Comment by offero** [comment]
The code has the `client` instance as a module level global, so each call to initialize the configuration would overwrite the previous. Each client instance would have to be scoped to get the behavior you want. Maybe something like a named connection would work where the library would keep track of multiple database connections by some sort of name and the default undefined or empty string name would work like normal.

**Comment by jeremydaly** [comment]
This is now possible because of the change made in #25.

**Comment by sam26880** [comment]
@jeremydaly how would you handle a case where you need to JOIN multiple databases in the same query?

**Comment by jeremydaly** [comment]
Hi @sam26880,

You would need to make sure that your credentials have access to both databases (this is assuming they are on the same server, of course) and then just reference them in your query. For example:

```sql
SELECT T1.id as idX, T2.id AS idY FROM databaseX.sometable T1
INNER JOIN databaseY.someothertable T2 ON T1.someval = T2.someval
```

Hope that answers your question,
Jeremy

**Comment by sam26880** [comment]
Ok. Nevermind. I just realized that it was proposed that we leave the database name out of the config and use it directly in the query. Ofc, with that approach it makes sense. 

Thanks again for a great library :)
