### ISSUE TITLE
Processes stuck on running the function getTotalConnections

### ISSUE THREAD

**Issue by jzhudev** [jeremydaly/serverless-mysql#150]
Sometimes the CPU will become 100% because of many processes running the query "SELECT COUNT(ID) as total, MAX(time) as max_age FROM information_schema.processlist". Please see the attached screenshot. Any suggestions would be appreciated. Thanks!

<img width="1216" alt="Screenshot 2023-07-18 at 21 04 57" src="https://github.com/jeremydaly/serverless-mysql/assets/12757367/1c4d697b-278c-4fb8-9755-1d9ab17bd969">

**Comment by naorpeled** [comment]
hey @jzhudev,
thanks for opening this issue,

It is currently possible to set `manageConns` to `false`, by doing so, it will make sure that the query won't be run in those specific processes.
So I'd personally start with doing so for some processes if possible.

Is doing so feasible for you?

If not, mind sharing some more info on the processes that are running?

**Comment by jzhudev** [comment]
> hey @jzhudev, thanks for opening this issue,
> 
> It is currently possible to set `manageConns` to `false`, by doing so, it will make sure that the query won't be run in those specific processes. So I'd personally start with doing so for some processes if possible.
> 
> Is doing so feasible for you?
> 
> If not, mind sharing some more info on the processes that are running?

Hi @naorpeled, thank you for the reply. I saw some [discussion](https://dba.stackexchange.com/questions/317913/track-database-slow-down-in-real-time) about frequent query of information_schema.processlist may be slow.  I was thinking to set a higher `usedConnsFreq` and see how it works.  What do you think? Thanks!

here are more related discusssions:
https://bugs.mysql.com/bug.php?id=100049
https://ahmedahamid.com/stop-using-show-processlist/

**Comment by naorpeled** [comment]
> > hey @jzhudev, thanks for opening this issue,
> > It is currently possible to set `manageConns` to `false`, by doing so, it will make sure that the query won't be run in those specific processes. So I'd personally start with doing so for some processes if possible.
> > Is doing so feasible for you?
> > If not, mind sharing some more info on the processes that are running?
> 
> Hi @naorpeled, thank you for the reply. I saw some [discussion](https://dba.stackexchange.com/questions/317913/track-database-slow-down-in-real-time) about frequent query of information_schema.processlist may be slow. I was thinking to set a higher `usedConnsFreq` and see how it works. What do you think? Thanks!
> 
> here are more related discusssions: [bugs.mysql.com/bug.php?id=100049](https://bugs.mysql.com/bug.php?id=100049) [ahmedahamid.com/stop-using-show-processlist](https://ahmedahamid.com/stop-using-show-processlist/)

Sounds like a great idea :)

Did you end up trying it ?

**Comment by naorpeled** [comment]
Hey,
i'm closing this issue as completed.
If you have any further questions, feel free to ping me 🙏
