### ISSUE TITLE
Wrapper for mysql2 ?

### ISSUE THREAD

**Issue by placeposition** [jeremydaly/serverless-mysql#153]
I would love to use this module but I much prefer the placeholder features in mysql2 over mysql. It is forgiving of extra key:values in the params which is gold.

```
let params = {
        cust_id: 1,
        day: 999,
};

const sql = `SELECT * FROM example WHERE cust_id = :cust_id AND day = :day`;

const [_arr] = await mysql2.query(sql, params);

```
Did I miss something and am making a daft request - (self-taught bozo here)

**Comment by naorpeled** [comment]
Hey @placeposition,
specifying the following in your serverless-mysql config should do the trick.
```javascript
{
    ///...
    library: require('mysql2')
}
```


Let me know if you have any questions :)

**Comment by x71c9** [comment]
I am trying to implement 'mysql2' with typescript, however when trying to set the attribute library to 'mysql2' I get the error that the attribute library expect a `Function`:

```typescript
import serverless_mysql from 'serverless-mysql';
import mysql2 from 'mysql2';

const mysql = serverless_mysql({
  config: {
    host     : db_host,
    database : db_name,
    user     : db_user,
    password : db_password,
    library: mysql2
 // ~~~~~~~ --------------------> Type 'typeof import("node_modules/mysql2/index")' 
 // is missing the following properties from type 'Function': apply,
 // 3 export call, bind, prototype, and 6 more. (tsserver 2740)
  },
})
```

Is there any support for typescript?

**Comment by anaerobic** [comment]
> I am trying to implement 'mysql2' with typescript, however when trying to set the attribute library to 'mysql2' I get the error that the attribute library expect a `Function`:
> 
> ```ts
> import serverless_mysql from 'serverless-mysql';
> import mysql2 from 'mysql2';
> 
> const mysql = serverless_mysql({
>   config: {
>     host     : db_host,
>     database : db_name,
>     user     : db_user,
>     password : db_password,
>     library: mysql2
>  // ~~~~~~~ --------------------> Type 'typeof import("node_modules/mysql2/index")' 
>  // is missing the following properties from type 'Function': apply,
>  // 3 export call, bind, prototype, and 6 more. (tsserver 2740)
>   },
> })
> ```
> 
> Is there any support for typescript?

@x71c9 it isn't idiomatic TS but you can do something akin to the following:

```ts
import mysql from 'serverless-mysql'
import * as mysql2 from 'mysql2'
import * as mysql2Promise from 'mysql2/promise'

// type is mysql.ServerlessMysql
const _mysql = mysql({
  library: mysql2 as any
})

const client = _mysql.getClient() as unknown as mysql2.Connection
client.config.namedPlaceholders = true

// type is mysql2Promise.Connection
const connection = await client.promise()

// then use it like you normally would
const [rows] = await connection.query({ sql, timeout, }, values)

...
```

**Comment by naorpeled** [comment]
> I am trying to implement 'mysql2' with typescript, however when trying to set the attribute library to 'mysql2' I get the error that the attribute library expect a `Function`:
> 
> ```ts
> import serverless_mysql from 'serverless-mysql';
> import mysql2 from 'mysql2';
> 
> const mysql = serverless_mysql({
>   config: {
>     host     : db_host,
>     database : db_name,
>     user     : db_user,
>     password : db_password,
>     library: mysql2
>  // ~~~~~~~ --------------------> Type 'typeof import("node_modules/mysql2/index")' 
>  // is missing the following properties from type 'Function': apply,
>  // 3 export call, bind, prototype, and 6 more. (tsserver 2740)
>   },
> })
> ```
> 
> Is there any support for typescript?

Hey @x71c9,
as @anaerobic mentioned, 
you can use `// @ts-ignore` / `// ts-expect-error` / `as any` to suppress the errors.
The underlying implementation uses the library that you specify, thus, supports their syntax.

The current type definitions of `serverless-mysql` are not refined enough when it comes usage of a custom library.
I'm trying to think of a decent way to approach this.

In any case this shouldn't be a blocker to using the core functionality of the library.

**Comment by naorpeled** [comment]
Marking this as completed, 
feel free to ping me if you have any additional questions/thoughts.
