### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'slice')

### ISSUE THREAD

**Issue by LamaAgent** [jeremydaly/serverless-mysql#155]
Hi, I get this error when I use serverless-mysql together with nextjs:
```
TypeError: Cannot read properties of undefined (Lesen von 'slice')
    at Object.connect (webpack-intern:///(middleware)/./node_modules/serverless-mysql/index.js:97:23)
    at async isSessionValid (webpack-intern:///(middleware)/./src/app/lib/db.ts:107:5)
    bei async isAuthenticated (webpack-intern:///(middleware)/./src/app/lib/actions.ts:108:10)
```

**Comment by LamaAgent** [comment]
That was actually my mistake because my credentials were invalid. However, a clearer error message would be nice.

**Comment by LamaAgent** [comment]
Nvm, it still ain't working

**Comment by naorpeled** [comment]
Hey @LamaAgent,
could you please specify how do you initialize `serverless-mysql`?

**Comment by naorpeled** [comment]
Closing this issue for now as it is stale.
@LamaAgent feel free to ping me if you need anything.
