### ISSUE TITLE
Do you have something like this for mongo db?

### ISSUE THREAD

**Issue by jonathanalberghini** [jeremydaly/serverless-mysql#16]
I am using the mongodb native driver 3.1.13. I am trying to find out how to do this with mongo.
If I have high usage and someone deploys a new version there are connection hanging out for 10 to 15 minutes. I tried to catch node  on exit but it doesn;t work with lambda.

**Comment by jeremydaly** [comment]
Hi @jonathanalberghini,
Unfortunately I only have this for built for MySQL. However, the same type of connection management components could apply. This project is open source, so feel free to see if there is a way to use my code and just modify it for Mongo.
