### ISSUE TITLE
FYI: Serverless-mysql2

### ISSUE THREAD

**Issue by bherila** [jeremydaly/serverless-mysql#160]
Hi! First, Thanks for creating this great package which I've been loving for years.

I just wanted to provide a heads-up that I have created and published a fork `serverless-mysql2` based on this repo

I don't really intend to _compete_, but it just seemed that this repo has been stagnant for a while, and I don't want to pull in the `mysql` (2 years' deprecated package) dependency when I actually need `mysql2`

Please feel free to send PRs there if you'd like and I will be happy to review and publish them.

Would we like to add a link to the README here, or remove the duplicated content from the README there? I'm open to whatever :D

**Comment by naorpeled** [comment]
Hey @bherila ,
Thanks for opening this thread :)

Regarding the dependency change, it's possible to use `mysql2` using the library option.

In addition, I think it's probably time to release a new major that removes the mysql dependency and replace it with mysql2.

If you want to help with issues here, let me know, we'd love to have some help 😎

**Comment by bherila** [comment]
I did try that library option, but unfortunately, the legacy MySQL package which is conditionally imported in this package, still ends up in my server bundle. This causes it to exceed the limitation of my Cloudflare worker size. I know that the Cloudflare team is working on bundle size optimizations, but until then my hands are tied 😪

we’ll see what I can do about some of the other open issues, just don’t want to promise too much upfront!

**Comment by naorpeled** [comment]
> I did try that library option, but unfortunately, the legacy MySQL package which is conditionally imported in this package, still ends up in my server bundle. This causes it to exceed the limitation of my Cloudflare worker size. I know that the Cloudflare team is working on bundle size optimizations, but until then my hands are tied 😪
> 
> we’ll see what I can do about some of the other open issues, just don’t want to promise too much upfront!

I completely understand that conern, I'll make sure to publish a new major with the dependency breaking change ASAP (probably later today).

And regarding other issues, it's all good!
No need to promise anything, if you want to be assigned to any of the issues feel free to ping me.

**Comment by naorpeled** [comment]
@bherila do you want to open a PR to replace mysql with mysql2? I can also do it but don't want to take it from you if you want to do it🙏

**Comment by bherila** [comment]
You can do it if you have time, otherwise I can do it tonight. I’m not territorial, no worry at all.
________________________________

**Comment by bherila** [comment]
Actually I'll try to do it quickly now
