### ISSUE TITLE
Has anyone tested this with Azure MySQL and Azure Functions?

### ISSUE THREAD

**Issue by rsre** [jeremydaly/serverless-mysql#17]
Documentation claims it should work in Azure without problems, but I want to check if anyone has used it before.

Any comments or help is welcomed.

**Comment by jeremydaly** [comment]
I have not tested with Azure, but there is nothing AWS specific about the implementation.

**Comment by rsre** [comment]
If I have time I'll give it a test. Thanks for the reply and your nice work!
