### ISSUE TITLE
ETIMEDOUT

### ISSUE THREAD

**Issue by navigiljshuusko** [jeremydaly/serverless-mysql#19]
Hi,

I'm seeing small number of ETIMEDOUT errors when connecting to Aurora RDS (less than 10/5000 lambdas a day - not in production yet) . This may be related to the fact that I'm using IAM and authentication tokens for logins.

I've added ETIMEDOUT into tooManyConnsErrors and the normal retry routine seems to handle this.

`
const tooManyConnsErrors = [
	'ER_TOO_MANY_USER_CONNECTIONS',
	'ER_CON_COUNT_ERROR',
	'ER_USER_LIMIT_REACHED',
	'ER_OUT_OF_RESOURCES',
	'ER_CON_COUNT_ERROR',
	'PROTOCOL_CONNECTION_LOST', // if the connection is lost
	'ETIMEDOUT', // if the connection times out
];
`

-jari

**Comment by jeremydaly** [comment]
Thanks for the report!
