### ISSUE TITLE
Error "ER_EMPTY_QUERY" when performing transaction

### ISSUE THREAD

**Issue by monisnap-julien** [jeremydaly/serverless-mysql#20]
Hello,

When i'm trying to use transaction, i always get an error "ER_EMPTY_QUERY". Here is a simple example :
````javascript
return await mysql
    .transaction()
    .query("SELECT * FROM myTable")
    .rollback(e => {
      console.log(e)
    })
    .commit()
````

Could you help me solve this issue please ?

Thanks in advance !

**Comment by monisnap-julien** [comment]
I think i found the issue. It's in the commit function, during the for loop (line 324-329) : 
````javascript
for (let i in queries) { /* THIS LINE */
  // Execute the queries, pass the rollback as context
  /* CONFLICT WITH NEXT LINE */
  let result = await query.apply({rollback},queries[i](results[results.length-1],results))
  // Add the result to the main results accumulator
  results.push(result)
}
````
`i` is an object, not an index
I will make a pull request with the correction.

**Comment by jeremydaly** [comment]
Thanks for this.

**Comment by jeremydaly** [comment]
Hi @monisnap-julien,

`queries` is an array, so `i` would be the key, which in this case would be a numerical index. All of the testing has this working correctly for me.

Did changing this actually fix your issue? What version of Node are you running?

Thanks,
Jeremy

**Comment by monisnap-julien** [comment]
In your original for loop, `i` is a value (of type function) in `queries` array (which contain functions). So i don't know how it's working on your side...
I tried changing `queries[i]` to simply `i` but it didn't work on my side. That's why i wrote it with an old javascript for loop. I'm using  nodejs 8.10.
