### ISSUE TITLE
Named Placeholders

### ISSUE THREAD

**Issue by nbunney** [jeremydaly/serverless-mysql#22]
I am wondering if you will be supporting `namedPlaceholders` like https://coderwall.com/p/196wpg/enable-named-placeholders-in-node-mysql

I have been using mysql2 for my coding up to this time and it is going to be a LOT of work to move all of that away from named placeholders.  I am very motivated by the scalability but going away from named to generic is a little scary to me since there is a much greater danger to get things transposed and cause errors.

**Comment by navigiljshuusko** [comment]
Hi,

I did my own customizations to use mysql2 and have not  had too many problems with that. I did this to support named parameters and IAM tokenized logins to AWS Aurora.

You may find details here if you like to try.

https://github.com/jeremydaly/serverless-mysql/issues/14


-jari huuskonen

**Comment by nbunney** [comment]
I saw your stuff before.  But doesn't that just ignore this library and use MySQL2 instead for the query executions?

**Comment by jeremydaly** [comment]
Hi @nbunney. It looks like named placeholders are just a client side implementation: https://github.com/sidorares/node-mysql2/blob/master/documentation/Extras.md#named-placeholders

I really like the `mysql` package, so unless there is another compelling reason to switch to `mysql2`, I'd prefer to implement this directly. 

@navigiljshuusko, can you not achieve IAM tokenized logins with the `mysql` package?

**Comment by nbunney** [comment]
I agree @jeremydaly stay on the course you are on and add the named placeholders to that.  Thanks for getting back to us!  Wish I had time to do the PR myself, but right now is not the right time for me.  :-)

**Comment by navigiljshuusko** [comment]
Hi,

I tried make it work with mysql but could not get it working. If I remember correctly it was about auth switch handler which was not found in mysql. And I could not find any example with mysql only with mysql2.

-jari

**Comment by navigiljshuusko** [comment]
I believe this work the same way as the library. I just added the execute-function the same way as query was implemented. It does the retries, promises and rest the same way as the original library.

Of course this breaks the connection to library fixes and upgrades which is a shame.

-jari

**Comment by jeremydaly** [comment]
You can now specify your library, so named placeholders would be possible with `mysql2`. I'm closing this for now.
