### ISSUE TITLE
The connection is null using getClient

### ISSUE THREAD

**Issue by ntranvinh** [jeremydaly/serverless-mysql#31]
Hi,
I think the library has an issue, I have some ts code bellow:
version: "serverless-mysql": "^1.3.0",
```
import mysql from "serverless-mysql";
 const mysqlInstance = mysql({
    config: {
      host     : configuration.db.host,
      user     : security.db.user,
      password : security.db.password,
      database : configuration.db.name,
      multipleStatements: true,
    },
  });
  console.log(await mysqlInstance.getClient());
```
The getClient return null here, is there anything I missed?
Please feel free to close this if you find it is duplicate (I have checked the issue list anyway to find any duplication) or I am doing wrong.
Thank you.

**Comment by jeremydaly** [comment]
Hi @ntranvihn,
You need to call the `connect()` method first. The configuration just sets up the connection, it doesn’t actually connect to the MySQL instance until you call `connect()` or run a query.
- Jeremy

**Comment by ntranvinh** [comment]
Hi @jeremydaly , wonderful. Do you think the document should be updated? Anyway, I close this now. Thank you.
