### ISSUE TITLE
How we can update in transactions

### ISSUE THREAD

**Issue by prataprockerss** [jeremydaly/serverless-mysql#32]
Hello, 
Thank you for an awesome package. 

As we are migrating MySQL package with your this package. Somewhere in our requirement, we need to update query inside transactions. 

For the demo,  I am Inserting into the same table. **But I want to update instead**

```
let result = await con
            .transaction()
            .query('INSERT INTO demoTable SET ? ', [
                {
                    name: "Parent",
                    parent_id: 0
                }
            ])
            .query(r => {
                let mulitInsert = [];
                for (let i = 0; i < users.length; i++) {
                    const element = users[i];
                    let arr = [
                        'INSERT INTO demoTable (name,parent_id) VALUES ? ',
                        [{ name: element, parent_id: r.insertId}]
                    ]
                    mulitInsert.push(arr)
                }
                // console.log(mulitInsert)
                return mulitInsert;
                
            })
            .rollback(e => {
                console.log("rollback error", e);
            }) 
 // optional
            .commit();
```

**Comment by jeremydaly** [comment]
Hi @prataprockerss,

Do you need to run an `UPDATE` query, or alter the query statement? There is an additional parameter passed into each `query` chain that contains an array with ALL the previous query results. I'm not sure what you're trying to accomplish. 

- Jeremy

**Comment by prataprockerss** [comment]
As we have a chaining method while making `query` in `transaction`. I want to loop update multiple tables in a loop inside the 2nd query. 

I hope I am clear.

**Comment by jeremydaly** [comment]
Hi @prataprockerss,

In this case you would need to do a "bulk insert", sending in an array of arrays as the second parameter.

```javascript
  .query(r => {
    let sql = `INSERT INTO demoTable (name,parent_id) VALUES ?`
    let multiInsert = []
    for (let i = 0; i < users.length; i++) {
      const element = users[i];
      let arr = [{ name: element, parent_id: r.insertId}]
      multiInsert.push(arr)
    }
    return [sql, mulitInsert]          
  })
```
Hope that makes sense.

Jeremy
