### ISSUE TITLE
Transaction handling - strange behaviour

### ISSUE THREAD

**Issue by SebastianApel** [jeremydaly/serverless-mysql#34]
Hi Jeremy, 
first: thank you for the package, it has made my life easier. I tried to use the transactions, but came across very strange behaviour (see below). Not sure if this is a bug in your package, or a problem with MYSQL 5.7.26... Anyway, I'm starting here. I have another suggestion for transactions, I'll open another issue for that.

=> Observed behaviour
I wanted to roll back a transaction on an InnoDB table. But the rollback was not successful - instead, the connection behaved as if auto commit was still "on".

=> Expected behaviour
Roll back my transaction

=> Workaround
When I added two queries ("SET AUTOCOMMIT=0" and "BEGIN") at the beginning of the transaction (like this .transaction().query("SET AUTOCOMMIT=0").query("BEGIN") the transaction rolled back as expected.

**Comment by jeremydaly** [comment]
This is curious. I've never had a problem with InnoDB tables since the library uses `START TRANSACTION` and `COMMIT`/`ROLLBACK` per the docs. The only time you should need to use `SET AUTOCOMMIT=0` would be if you were using a MyISAM table. This library assumes (for transactions, anyway) that you are using the InnoDB engine.

Have you noticed this behavior in other version of MySQL, besides 5.7.26?

**Comment by SebastianApel** [comment]
@jeremydaly Yes, definitely curious. I've only tested 5.7.26. The table is definitely an InnoDB table, I just double checked. I can reproduce the behaviour if I include an invalid SQL statement into the transaction after an INSERT statement. As expected, there's an exception because of the invalid SQL, and ROLLBACK is called, but I afterwards  can see the (partial) data in MySQL Workbench. 

Maybe it has something to do with the way the transaction is processed (i.e. not as a "multiple statements" via one "query" call). But I have to admit I'm far into guessland here.

BTW: The assumption regarding InnoDB is not in the README - it might be helpful to add that to the transaction section, because it might save inexperienced MySQL users trouble.

**Comment by jeremydaly** [comment]
Adding a comment to the README about InnoDB. I have not seen any other issues with this, so I'm closing it for now. Please let me know if this happens again.
