### ISSUE TITLE
Use import 

### ISSUE THREAD

**Issue by bluedusk** [jeremydaly/serverless-mysql#37]
I used to use import as below instead of require with v1.3, but its not working any more with v1.4. And I cant `import serverlessMysql from "serverless-mysql"` use either.

Can anyone suggest how to use import with 1.4 ?
```
import * serverlessMysql from "serverless-mysql"
const mysql = serverlessMysql({
	config: {
		host: host,
		database: db,
		user:user
		password: psw
	}
})

```

**Comment by kernwig** [comment]
Took a little fiddling, but found this:

```
import serverlessMysql, {ServerlessMysql} from "serverless-mysql";
```

**Comment by jeremydaly** [comment]
Awesome! Thanks for figuring this out!

**Comment by kernwig** [comment]
Sadly, by solution compiles just fine, but `serverlessMysql` is `undefined` upon execution.

As far as I can see, ES2015 syntax simply does not have a way of importing the "function module" export as used in serverless-mysql. We have to stick with native Node.js ways (require function):

```
import {ServerlessMysql} from "serverless-mysql";
const mysql: ServerlessMysql = require("serverless-mysql")({
	config: {
		host: host,
		database: db,
		user:user
		password: psw
	}
})
```

**Comment by tomchiverton** [comment]
The above doesn't work under Node v14 on Lambda.

This does

```
import ServerlessMysql from "serverless-mysql";
var mysql = ServerlessMysql();
mysql.config({
      host   : process.env.RDS_HOST,
      user   : process.env.RDS_USER,
      password : mysql_password
    })
```
