### ISSUE TITLE
use with AWS.SecretManager

### ISSUE THREAD

**Issue by vgrafe** [jeremydaly/serverless-mysql#38]
Hi! I use secret manager to provide DB credentials to my serverless app. 

```js

const client = new AWS.SecretsManager({
  region: 'us-east-1'
});

// later on...
const secret = await client.getSecretValue({ SecretId }).promise();

```

The problem: getting those credentials with `getSecretValue` is an synchronous operation, so setting up the connection can't be done outside of the main handler...

Am I missing something out?

**Comment by vgrafe** [comment]
Closing - I made it work by implementing a singleton that initially returns a promise to handle if the connection is accessed before being available.

**Comment by disbelief** [comment]
@vgrafe do you happen to have a sample code snippet you could share with your solution? I'm a little unclear what you mean re. the singleton.

**Comment by aldentinker** [comment]
@vgrafe I would also like to know how you achieved this.

**Comment by vgrafe** [comment]
Sure. Here is the `db.js` file:

```js
let _cnx, _promiseSuccess;

const init = async () => {
  const secret = require('./secret');
  const creds = await secret.get('db-credentials');
  const credentials = JSON.parse(creds);

  const mysql = require('serverless-mysql')();

  mysql.config({
    host: credentials.host,
    user: credentials.user,
    password: credentials.password,
    database: credentials.database,
    port: credentials.port
  });

  const query = async (...args) => {
    const results = await mysql.query(...args);
    await mysql.end(); // performs sconnection management tasks
    return results;
  };

  if (_promiseSuccess) {
    _promiseSuccess({ query });
  }

  _cnx = {
    query
  };
};

const getCnx = async () => {
  if (!_cnx) _cnx = new Promise(success => (_promiseSuccess = success));
  return _cnx;
};

module.exports = { init, getCnx };
```

Now it is initialized as follows in the `handler.js` file - please note that this needs to be on top level, outside of the handler methods:
```js
const db = require('./db');
(async () => await db.init())();
```


Finally, you get a db connection as follows:
```js
const { getCnx } = require('./db');
const db = await getCnx();
const rows = await db.query('select * from some_table');
```

I hope this is clear. Got this working on production, it runs as expected.

**Comment by disbelief** [comment]
Awesome, yes it's clear. Thanks for taking the time to post this @vgrafe

**Comment by disbelief** [comment]
@vgrafe a question if I may: why are you calling `await mysql.end();` in the `query` method? What if I wanted to perform multiple queries from the same handler? Also curious why `mysql.connect()` is never called in your `init` function?

**Comment by jeremydaly** [comment]
@disbelief,

He's running `mysql.end()` before `return`ing from the function. You can run as many queries as you want, but before you `return`, you need to make sure you call the `.end()` clean up function.

There is no need to explicitly call `mysql.connect()`, as this will be done the first time a query is run if the connection doesn't exist. It is possible that your function (through some conditional flow) doesn't need to connect to the database, but instead can respond without it. This just-in-time connection workflow helps to minimize unnecessary connections.

Hope that makes sense,
Jeremy

**Comment by disbelief** [comment]
@jeremydaly ah I see thanks. 

So just to confirm: I can call `.query` multiple times from my handler even though there's a `.end()` in that function because it will re-connect if `.end` was already called previously?

**Comment by vgrafe** [comment]
I didn't think of this. 

I'd address this by removing that `await mysql.end();` line from the query method, expose that `.end()` method through a new export, and import/call it in your handler once you know no more db use will happen.

**Comment by jeremydaly** [comment]
@vgrafe, there is no need to wrap the `mysql` require statement in your `init()` function. If you set that outside of the main handler and use it as a global variable, you can just call `mysql.config()` after you retrieve your parameters.

That way, `mysql.query()` and `mysql.end()` would be available in your main handler.

**Comment by vgrafe** [comment]
You're right! I'm a bit busy these days, but I will update and post the optimized code here as soon as I find the time.

**Comment by disbelief** [comment]
@vgrafe 
> expose that .end() method through a new export, and import/call it in your handler once you know no more db use will happen.

FWIW I'm just exposing the resulting mysql connection via the export and letting the caller decide what to do with it (`.query()`, `.transaction()`, `.end()`, etc.)

**Comment by disbelief** [comment]
My code based on this conversation, should anyone find it useful:

**db.js**
```javascript
import MySQLServerless from 'serverless-mysql';
import getDatabaseConfig from 'secrets';

let connection, resolveConnectionWhenReady;

const connect = async () => {
  const config = await getDatabaseConfig();

  connection = MySQLServerless({ config });

  if (resolveConnectionWhenReady) {
    resolveConnectionWhenReady(connection);
  }
}

const getConnection = async () => {
  if (connection) {
    return connection;
  }
  // in case getConnection was called before connect
  return new Promise(resolve => (resolveConnectionWhenReady = resolve));
}

export default { connect, getConnection };
```

**myLambdaFunction.js**
```javascript
import db from './db';

(async () => await db.connect())();

export const handler = async (event, context) => {
  context.callbackWaitsForEmptyEventLoop = false;

  const mysql = await db.getConnection();

  const widgets = await mysql.query('SELECT * FROM widgets');
  // ... whatever business logic

  await mysql.end();
};
```

**Comment by jeremydaly** [comment]
Hmm, I don't think that async call to `db.connect()` outside your handler will actually work. You likely just need the `const mysql = await db.getConnection();` line inside your handler and that will work fine.

**Comment by disbelief** [comment]
Seems to be working... `db.connect()` in this case isn't calling connect on the underlying mysql connection. I probably should have named that `db.init()` or something else to avoid naming confusion.

**Comment by jeremydaly** [comment]
Yeah, I see that you're not actually connecting, just loading the credentials. However, last time I checked, `async/await` was ignored outside of the handler. So it looks like your `db.getConnection()` is what is waiting for the SSM call to finish/resolve before moving on. 

Basically, you don't need the `async` in front of `db.connect()`, because it isn't going to wait for it anyway, the `getConnection()` inside the handler will. The other (potential) problem with this approach is that your `db.connect()` will only run on Cold Starts. *IF* that `connection` variable somehow goes away, `getConnection()` wouldn't trigger SSM to reload the credentials.

I think you'd be better off just having the `getConnection()` function call your `connect()` function if `connection` didn't exist. You'll still get reuse, can remove the call to `connect()` outside your handler, and then you don't have to worry about potential variable overwrites.

Just a thought.

**Comment by disbelief** [comment]
That sounds like a simpler approach. Seems like the important thing is to ensure that there's a global `connection` variable that persists outside calls to the handler. Inside the handler it's fine to `await` for the connection to actually be setup, if it hasn't been already.

**Comment by disbelief** [comment]
Picture being worth a thousand words, here's my updated code:

**db.js:**  _(edited 10/10/2019 after @SebSchwartz's comment)_
```javascript
import MySQLServerless from 'serverless-mysql';
import { getDatabaseConfig } from 'secrets';

let connection, connectionPromise;

const connect = async () => {
  const config = await getDatabaseConfig();
  connection = MySQLServerless({ config });
  return connection;
};

const getConnection = async () => {
  if (connection) {
    return connection;
  }
  if (connectionPromise) {
    return connectionPromise;
  }
  connectionPromise = connect();

  return connectionPromise;
};

export default { getConnection };
```

**myLambdaFunction.js:**
```javascript
import db from './db';

export const handler = async (event, context) => {
  context.callbackWaitsForEmptyEventLoop = false;

  const mysql = await db.getConnection();

  const widgets = await mysql.query('SELECT * FROM widgets');
  // ... whatever business logic

  await mysql.end();
};
```

**Comment by SebSchwartz** [comment]
Hey,
First of all, thanks for the code sharing @vgrafe  and @disbelief ;)

I can still not make it work with the last code of @disbelief , i'm still getting too many connections errors :( 

FYI, in your last code @disbelief , you are no longer assigning connection.

Is this stil the code you are using?

Thanks a lot

**Comment by disbelief** [comment]
@SebSchwartz it's working for me but depending on your throughput there's no guarantee there will be zero connection errors. You may need to tweak your MySQL configuration, scale up the cluster, etc.

btw nice catch re `connection` not being assigned. My codebase is structured a little differently so I had transposed my logic into the above snippet. The `connection` should be assigned to the result of `MySQLServerless()` in the `connect` function.
