### ISSUE TITLE
Manually rollback a transaction.

### ISSUE THREAD

**Issue by ImpliedHuman** [jeremydaly/serverless-mysql#39]
Hey,

I'm quite new to MySQL and to serverless so I was wondering if you could help me out on a transaction I'm trying to perform using this library. 

I have two tables: one saves messages and the other stores which user liked which message. When a user likes a message I increment a likes field and add that user to the table so I know who liked what. When adding this user/message-pair to the DB the PK constraint automatically checks if this user hasn't yet liked this message before and will rollback the transaction if he has. When unliking though deleting a row that doesn't exist does not automatically fail the commit so I want to do this manually (a user can only unlike if he has previously liked the post so no 'negative' likes are allowed). This is the code that I have come up with so far, I have marked the problem with a TODO:

``` js
let results = await mysql.transaction()
  .query('DELETE FROM user_message_liked WHERE user_id = ? AND message_id = ?', [event.user_id ,event.message_id])
  .query((r) => {
    // Check if delete actually removed any rows
    if (r.affectedRows == 0) {
      // TODO: Here I want to rollback/cancel this transaction.
    }
    return ['UPDATE message SET likes = likes - 1 WHERE user_id = ? AND message_id = ?', [event.user_id, event.message_id]];
  })
  .rollback(e => { console.log('Rollback: ', e) }) // optional
  .commit(); // execute the queries
```
I have tried `return ['COMMIT'];` and at first glance that seems to do the job but I'm not sure if it is the right/best way to do it. For example, what would happen if I were to chain another query after that.

Is this possible or am I just on the wrong track?

Thanks in advance!

**Comment by jeremydaly** [comment]
Hi @Benassou,

Sorry for the late reply. If you throw an error in your `// TODO` section, this should trigger `serverless-mysql` to issue a `ROLLBACK` command to MySQL. However, if the `user_message_liked` record doesn't exist, there would be nothing to rollback.

Instead, I would just make the UPDATE conditional, so instead of what you have, do this:

```javascript
let results = await mysql.transaction()
  .query('DELETE FROM user_message_liked WHERE user_id = ? AND message_id = ?', [event.user_id ,event.message_id])
  .query((r) => {
    // Check if delete actually removed any rows
    if (r.affectedRows > 0) {
     return ['UPDATE message SET likes = likes - 1 WHERE user_id = ? AND message_id = ?', [event.user_id, event.message_id]];
    } else {
      return ['SELECT 1']
    }
  })
  .rollback(e => { console.log('Rollback: ', e) }) // optional
  .commit(); // execute the queries
```

You can't issue blank queries, so the `SELECT 1` just returns `1`. This way your `DELETE` will fire and the `UPDATE` will be part of that transaction. If the `UPDATE` fails, it'll rollback the `DELETE` as well.

Hope that makes sense,
Jeremy

**Comment by ImpliedHuman** [comment]
Thank you!

**Comment by carlosfer02** [comment]
I really need to call the rollback function. I tried to throw an error like this:

```
let results = await mysql.transaction()
                .query('UPDATE clients SET user=? WHERE id=1', ['fer'])
                .query((r) => {
                    throw({ status: 0, msg: 'something wrog happend'});
                })
                .rollback(e => {
                    console.log('rollback');
                    console.log(e);
                })
                .commit();
```

But my rollback block is never called. 

Is there anyway to force the rollback block?

**Comment by jeremydaly** [comment]
You don’t need the `.connection` bit in there. Just do `mysql.transaction`.

**Comment by carlosfer02** [comment]
> You don’t need the `.connection` bit in there. Just do `mysql.transaction`.

Oh, sorry, I use like library for your library, just ignore that connection. I am able to perform queries very well, I just have this problem with transactions.
