### ISSUE TITLE
Example for Events

### ISSUE THREAD

**Issue by abhijits3** [jeremydaly/serverless-mysql#40]
Do you have any example on using events, especially onConnectError and onError to handle custom response.

**Comment by JustinLutsky** [comment]
I'd also find this really helpful. Thanks!

**Comment by jeremydaly** [comment]
Hi @abhijits3,

Here are some basics events:

```javascript
  onConnect: (client) => { console.log('MYSQL Connected:', client.threadId) },
  onConnectError: (e) => { console.log('MYSQL Connection Error:',e.message) },
  onClose: () => { console.log('MYSQL Connection Closed') },
  onError: (e) => { console.log('MYSQL Error:',e.message) },
  onRetry: (e,retries,sleep) => { console.log('RETRY',retries,sleep) },
  onKill: (zombie) => { console.log('Kill:',zombie) },
  onKillError: (e) => { console.log('Kill Error:',e.message) }
```
Many of the errors are **non-fatal** and `serverless-mysql` will handle the retries for you. Errors like `onConnectError` will retry several times before it throws a catchable error. So if you wanted to return a custom error, you would need to wrap your query (or `mysql.connect()`) in a `try-catch` block. 

If you want to throw a custom error from your `onConnectError` events, you can short circuit it by throwing an error in the reporting function:

```javascript
onConnectError: (e) => { 
  console.log('MYSQL Connection Error:',e.message) 
  // throw a custom error
  throw new Error('This is my custom connect error')
}
```

Hope that helps,
Jeremy

**Comment by notmessenger** [comment]
You have to set/define these in the initial `const mysql = require('serverless-mysql')({})` call.  This was initially throwing me.

**Comment by agrant-intix** [comment]
Hi @jeremydaly,

I'm newer to node and javascript so just looking to make sure I'm on the right track with how I've added this!

I've hidden a couple of lines regarding the sentry init, more just checking I've put the onError and onConnectError in the right place? 

const mysql = require('serverless-mysql');
const db = mysql({ config: { host: XXXX, database: XXXX, user: XXXX, password: XXXX }, onError: (e) => { Sentry.captureException(e); }, onConnectError: (e) => { Sentry.captureException(e); } } );

exports.query = async query => {
	try {
		const results = await db.query(query)
		await db.end()
		return results
	} catch (error){ 
		return { error } 
	}
}

**Comment by jeremydaly** [comment]
@agrant-intix, this looks right!
