### ISSUE TITLE
Unable to determine connection to database

### ISSUE THREAD

**Issue by AmoDinho** [jeremydaly/serverless-mysql#42]
# Environment

`serverless-mysql` version : ^1.4.0

# Problem

When trying to insert data into a table I get the following error message:

```
{
  "error": "Unexpected token S in JSON at position 1"
}
```

# Setup

Here is my code:

```

const Client = require('serverless-mysql')
export const addBook = async (args, context) => {



 var client = Client({
        config: {
            host: 'db_url',
            user: 'db_user',
            password: 'db_password',
            database: 'db_name',
        }
    })



    
    await client.connect()

   
    await client.query(`
    CREATE TABLE IF NOT EXISTS books
    (
        id MEDIUMINT UNSIGNED not null AUTO_INCREMENT
        title varchar(100) not null
        author varchar(100) not null
        PRIMARY KEY (id)
    );
    `)

    let book = await client.query('INSERT INTO books (title,author) VALUES(?,?)', [args.title ,args.author ]);
    await client.end()
  
    return book


}
```

I'm struggling to see where I've gone wrong...any help would be great 💇‍♂

**Comment by jeremydaly** [comment]
@AmoDinho,

Does the table get created? It could be an issue parsing the response.

Thanks,
Jeremy

**Comment by AmoDinho** [comment]
@jeremydaly , 

The table does not get created...

**Comment by jeremydaly** [comment]
Thanks, I'll take a look.

**Comment by jeremydaly** [comment]
I think the issue is with your `CREATE TABLE` syntax. You need commas after each field like this:

```sql
CREATE TABLE IF NOT EXISTS books
  (
    id MEDIUMINT UNSIGNED not null AUTO_INCREMENT,
    title varchar(100) not null,
    author varchar(100) not null,
    PRIMARY KEY (id)
);
```

You can enable more detailed error reporting by wrapping your query in a `try-catch` block.

Hope that helps,
Jeremy

**Comment by AmoDinho** [comment]
Awesome let me give it a try quickly.  🚶 

Thanks for the quick response!

**Comment by AmoDinho** [comment]
Yeah the outcome is still the same... 😭

**Comment by jeremydaly** [comment]
Hmm, it worked for me. Let me try something else.

**Comment by AmoDinho** [comment]
I've config an AWS Aurora Serverless instance and and I'm running the function locally, do you think that it might be that I would need to allow traffic from my machine to the VPC of the instance?

**Comment by jeremydaly** [comment]
Most likely. You should make sure you can connect to your database first.

**Comment by AmoDinho** [comment]
From the terminal I am able to connect to it though.

**Comment by jeremydaly** [comment]
Did you figure this out?

**Comment by AmoDinho** [comment]
Good news is that it does create the table after I deployed it. Somehow it is not reading the arguments for the title and author (returning null). Also turns out I was using the cluster id and not an actually DB with in the instance 🤕 .

So I've gotta just figure that out and I should be in the clear!

Thanks for your help 💯 🏅
