### ISSUE TITLE
Types definition for Typescript

### ISSUE THREAD

**Issue by xamoulin** [jeremydaly/serverless-mysql#5]
That's it!

**Comment by liam-betsworth** [comment]
+1

**Comment by deptno** [comment]
I've tested with serverless@1.3.0. It seem to work

**Comment by shrugs** [comment]
I'm only able to import with

```
import create = require('serverless-mysql')
```

and my intellisense can't seem to import the type `ServerlessMysql` - is this expected?

**Comment by shrugs** [comment]
Additionally, the `Transaction` is actually a function returning that interface, not an object, so the existing type of 

```ts
transaction: Transaction
```

should be 

```ts
transaction(): Transaction
```

and

```ts
commit(): Promise<any>
```

could be

```ts
commit(): Promise<any[]>
```

**Comment by deptno** [comment]
@shrugs > import the type `ServerlessMysql` - is this expected?

Not expected, definition is very initial version, so many modifications will need more.

Can you review the commit? I applied your comment, https://github.com/deptno/serverless-mysql/commit/32df25f2f4d52d4c78a219d32277bda0e38c5c26

**Comment by jeremydaly** [comment]
Any additional help with TypeScript definitions would be greatly appreciated.

**Comment by kernwig** [comment]
I made these types for my own use. Something like them may be useful in the next iteration of this:

```
export interface DbQuery {
    /**
     * Template query
     */
    sql: string;

    /**
     * Values for template query
     */
    values?: any[];

    timeout: number;
}

/**
 * Return type from ServerlessMysql#query after performing a SQL INSERT
 */
export interface DbInsertResult {
    insertId: number;
}

/**
 * Return type from ServerlessMysql#query after performing a SQL DELETE
 */
export interface DbDeleteResult {
    affectedRows: number;
}

/**
 * Return type from ServerlessMysql#query after performing a SQL UPDATE
 */
export interface DbUpdateResult {
    changedRows: number;
}

/**
 * Return type from ServerlessMysql#query after performing a SQL SELECT
 * (Array of objects containing the requested table fields.)
 */
export type DbSelectResult = Array<any>;
```
