### ISSUE TITLE
Unable to close the connection[Lambda]

### ISSUE THREAD

**Issue by ashwanigowebbaby** [jeremydaly/serverless-mysql#50]
Hi Jeremy,
I tried to use serverless-mysql I m facing an issue with destroying the connection. I use the lambda example mentioned in the docs I m getting my output but my execution is not ending means lambda function is not closing by itself it's closing after timeout however I m getting the expected result from the query.

**Comment by jeremydaly** [comment]
Hi @ashwanigowebbaby,

Are you using callbacks or `async/await`? If you are using callbacks, you need to set  `context.callbackWaitsForEmptyEventLoop = false` inside your handler.

Hope that helps,
Jeremy

**Comment by ashwanigowebbaby** [comment]
Jeremy Thanks for your quick response.
 I m aware of it. and used it but the output is the same below is code

`
```
const mysql = require('serverless-mysql')({
    config: {
        host: process.env.DBC_HOST,
        database: process.env.DBC_DATABASE,
        user: process.env.DBC_USER,
        password: process.env.DBC_PASSWORD
    }
})
exports.genrateProductsTemplate = async (event, context) => {
    context.callbackWaitsForEmptyEventLoop = false;
    // Run your query
    let results = await mysql.query('SELECT * FROM mytable')

    // Run clean up function
    await mysql.end()

    // Return the results
    return results
}
```

**Comment by jeremydaly** [comment]
Hmm. What permissions does your MySQL user have?

**Comment by jeremydaly** [comment]
Try running it without the `await mysql.end()` to see if that is causing the issue.

**Comment by ashwanigowebbaby** [comment]
Thanks again for the response.
 My Mysql user has all the permissions on that DB except  GRANT
I also tried without await but still hard luck

**Comment by jeremydaly** [comment]
Can you try calling `mysql.quit()` and see if that works?

**Comment by ashwanigowebbaby** [comment]
Thanks, Jeremy its work with above example code but it seems me an issue with live code I will look forward it. Thanks

**Comment by jeffski** [comment]
I was experiencing the same issue with results being returned but the Lambda execution not terminating and eventually timing out.

Replacing `await mysql.end()` with `mysql.quit()`, no `await` in front, worked for me. I also did not use `context.callbackWaitsForEmptyEventLoop = false;`.

Does this mean the connection will not be kept open for subsequent calls?

**Comment by jeremydaly** [comment]
Hi @jeffski,
What runtime are you using? Also, are you using async functions or callbacks?
Thanks,
Jeremy

**Comment by jeffski** [comment]
Hi, great response time. I'm using Node 10.x. My code is essentially like below right now:

```
const AWS = require("aws-sdk");
const mysql = require('serverless-mysql')({
  config: {
    host: process.env.HOST,
    database: process.env.DATABASE,
    user: process.env.USERNAME,
    password: process.env.PASSWORD
  }
})

module.exports.timeline = async (event, context, callback) => {
  const newImages = event.Records.map(
    (record) => AWS.DynamoDB.Converter.unmarshall(record.dynamodb.NewImage)
  );

  console.log('Converted records', newImages);

  let results = await mysql.query('SELECT * FROM my_table')

  mysql.quit();

  console.log(results);

  callback(null, 'OK');
};
```
Lambda handler receives events from Dynamo stream and will write data to RDS database. Right now I've just got a simple select which is showing correctly in CloudWatch logs. It times out with `await mysql.end()`.

**Comment by jeffski** [comment]
I need to return the result not fire the callback(), is that right? Looks like it here: https://docs.aws.amazon.com/lambda/latest/dg/nodejs-prog-model-handler.html#nodejs-prog-model-handler-callback

**Comment by jeffski** [comment]
That seems to work.

**Comment by jeremydaly** [comment]
Yes, issuing a `return` should fix that.
