### ISSUE TITLE
Support Knex.js 

### ISSUE THREAD

**Issue by Biktop** [jeremydaly/serverless-mysql#55]
I saw the similar question but any way if there're any way to use this library together with knex.js? It'd be useful because there're a lot of other libraries which based on knex.js (objection.js and etc).

**Comment by pianomansam** [comment]
I just provided an example on the previous issue mentioning knex.js

https://github.com/jeremydaly/serverless-mysql/issues/46#issuecomment-549478686

**Comment by Biktop** [comment]
Thanks for example. But in case when knex is used by other libraries (such as objections.js) you cannot do this ticks. 
But any way this library shows some useful techniques which can be reused.
