### ISSUE TITLE
How to use wildcards?

### ISSUE THREAD

**Issue by AmoDinho** [jeremydaly/serverless-mysql#56]
Hi @jeremydaly ,

I have the following query using a wildcard:

```
`SELECT book_id,book_title,book_image FROM book WHERE book_title LIKE "%'?'%"  `
```

But I get an empty array returned, however when running the query in MySQL Workbench it returns the relevant records.

Could you point out what I'm doing wrong please?

Thanks! 👯‍♂

**Comment by jeremydaly** [comment]
Sorry for the late reply. This library uses the `mysql` npm library by default. Question marks are used to replace escaped query identifiers (https://www.npmjs.com/package/mysql#escaping-query-identifiers), not as wildcards.

**Comment by AmoDinho** [comment]
Awesome! thanks for the help!
