### ISSUE TITLE
getClient returns null in random occasions

### ISSUE THREAD

**Issue by georgedail** [jeremydaly/serverless-mysql#62]
Using node 10 and node 12 on AWS Lambda
I get null from getClient in random occasions.
I can't post the exact code but it is something like this

```js
await mysql.connect();
let connection = mysql.getClient();
const response  = await mysql.query();
await mysql.end();
mysql.quit();
```

I need the connection to escape parameters to put in the query, but every few calls connection is null and after debugging the library I found that the error causing this is PROTOCOL_SEQUENCE_TIMEOUT.

This didn't happen when I was using node 8 but i have to upgrade since node 8 is reaching its EOL.

I don't have exact reproduce steps since it doesn't occur consistently, but it happens fairly often.

After looking around I saw that many people solved it by passing a callback function in mysql.end(). I modified the library but it didn't solve the problem

**Comment by jeremydaly** [comment]
Looking into this. Need to figure out if this is a Node 10+ issue.

**Comment by georgedail** [comment]
I kept looking into it and it seems like removing `mysql.quit()` solves this problem

**Comment by jeremydaly** [comment]
`mysql.quit()` should only be used to explicitly terminate the connection.

**Comment by georgedail** [comment]
Sorry for the late response. This is gone after removing `mysql.quit()`, we didn't need that anyway.
