### ISSUE TITLE
timing out intermittently

### ISSUE THREAD

**Issue by mohsinhere** [jeremydaly/serverless-mysql#63]
Hi,

I'm not sure if this is a serverless-mysql issue at all. I posted this in stackoverflow(https://stackoverflow.com/questions/59214160/rds-mysql-timing-out-intermittently-when-called-from-lambda-using-nodejs), but didn't get much help from there.

Below is my lambda function. Am I missing something here?

```
export async function get(event, context, callback) {
    if (await warmer(event)) return 'warmed';

    context.callbackWaitsForEmptyEventLoop = false;

    try {
        const userId = getUserIdFromIdentityId(event);
        const query = "select * from UserProfile where UserId = ?";

        const result = await mysql.query(query, [userId]);
        console.log(result);

        console.log('getting user account');

        mysql.quit();

        return success({
            profileSettings: result.length > 0 ? result[0] : null,
        });

    } catch(e) {
        console.log(e);

        return failure();
    }
}
```

Success function returns a json object like below

```
return {
        statusCode: 200,
        headers: {
            "Access-Control-Allow-Origin": "*",
            "Access-Control-Allow-Credentials": true
        },
        body: JSON.stringify(body)
    };
```

serverless-mysql is initialized using below code:
```
export const mysql = AWSXray.captureMySQL(require('serverless-mysql')({
    config: {
        host: process.env.dbHost,
        user: process.env.dbUsername,
        password: process.env.dbPassword,
        database: process.env.database,
    }
}));
```

Any help would be much appreciated. Thanks!

**Comment by jeremydaly** [comment]
I'm not sure wrapping the entire library with Xray will work. You should wrap the `mysql` library in Xray and then pass it in as the `library` option in the configuration object: https://github.com/jeremydaly/serverless-mysql#configuration-options

**Comment by mohsinhere** [comment]
Thanks for the quick response @jeremydaly  .Actually it does work... but as I said it times out intermittently. I added Xray to find out why it is timing out... but that didn't help much either... is the lambda function all good? 

Do we really need the `context.callbackWaitsForEmptyEventLoop = false;` when I'm not returning a callback? But it times out (intermittently) even if I remove that. I'm running out of ideas. :(

**Comment by mohsinhere** [comment]
Hi @jeremydaly, where should I add the onError event in my code? Sorry for my ignorance.

**Comment by mohsinhere** [comment]
I saw in this [thread](https://github.com/jeremydaly/serverless-mysql/issues/40) that serverless-mysql automatically tries to retry connection errors. My lambda time out is set at 10 seconds which is why I'm not able to see the actual error. 

Update1: I set the maxRetries to 1. Still there are no errors passed to the catch block. Lambda just times out eventually. Below is my my sql initialization code:

```
export const mysql = require('serverless-mysql')({
    config: {
        host: process.env.dbHost,
        user: process.env.dbUsername,
        password: process.env.dbPassword,
        database: process.env.database,
        library: require('mysql'),
        maxRetries: 1
    }
});
```

Update2: My query code looks like this now:

```
const result = await mysql.query({
            sql: query,
            values: [userId],
            onError: (e) => {
                console.log("MY SQL Error", e.message);
            },
            onConnectError: (e) => {
                console.log('MYSQL Connect Error', e.message);
            }
        });
```

It doesnt really go into the onError or onConnectError at all.

**Comment by mohsinhere** [comment]
switched from using serverless-mysql to mysql and there are no more time outs! Could be something wrong with the way I used serverless-mysql which I'm not sure of.
