### ISSUE TITLE
Cannot enqueue query error after Database failover (AWS RDS MySQL Aurora)

### ISSUE THREAD

**Issue by annjawn** [jeremydaly/serverless-mysql#7]
We migrated majority of our Lambda functions to use this library in our dev environment to give it a run and so far it has been working great. However, yesterday we faced an issue, which still continues to be an issue and I have no idea how to resolve this.

Approximately at noon on Sunday our dev RDS MySQL (Aurora provisioned instance) crashed, and then eventually failed over to the failover instance. The reason of the crash is still unknown but we are investigating, however it is worth mentioning that this is the first time the instance ever crashed in the past 1.5 years of continuous reliable usage. Once the failover was complete, we were able to connect to the DB and query normally, however, all the Lambda functions were now throwing this error (see below). This error, specifically started after the failover and also ALL Lambda functions that query our database seem to be facing this exact error as it reflected in Cloudwatch logs. We stopped and started the cluster, rebooted the cluster even hoping to resolve this issue but the error kept showing up and the API Gateway endpoints continued to return error. We looked in the database and there were no lingering sessions/processes to be found.

```
2018-09-30T22:25:42.908Z	c49a6ffc-c4ff-11e8-9665-c71a7d30630c	Error: { Error: Cannot enqueue Query after fatal error.
at Protocol._validateEnqueue (/var/task/node_modules/mysql/lib/protocol/Protocol.js:200:16)
at Protocol._enqueue (/var/task/node_modules/mysql/lib/protocol/Protocol.js:138:13)
at Connection.query (/var/task/node_modules/mysql/lib/Connection.js:200:25)
at Promise (/var/task/node_modules/serverless-mysql/index.js:185:23)
at new Promise (<anonymous>)
at Object.query (/var/task/node_modules/serverless-mysql/index.js:183:10)
at <anonymous> code: 'PROTOCOL_ENQUEUE_AFTER_FATAL_ERROR', fatal: false }
```

We ultimately switched over a couple of Lambda's to our native code which didn't use this library, but was using traditional MySQL js connection pool and handler callback, instead. Curiously enough, those functions happened to be working just fine (even with concurrent requests). Since then, we reverted back all of the Lambda functions to our previous version since none of our Lambda functions were operational at the time due to the error above, but I thought it would be worth raising this issue since I am not entirely certain what's causing it.

**Comment by jeremydaly** [comment]
Thanks for this report, @annjawn. I have not seen this error before with any of my production accounts, but I will investigate further.

**Comment by zigzhang** [comment]
@annjawn I've experienced similar errors as well.
What solve the issue for us was to `await mysql.end()` at the end of the handler (vs `mysql.end()` without `await`). 

I didn't spend much time trying to understand exactly what's happening under the hood, but now, I'm not encountering this issue anymore.

**Comment by jeremydaly** [comment]
@zigzhang, interesting find. The `mysql.end()` method does a bit of clean up, so that makes sense. @annjawn, I haven't been able to duplicate this issue, but I'll try and remove `await` from the `mysql.end()` call to see if that causes the issue.

**Comment by annjawn** [comment]
Thanks a lot @zigzhang and @jeremydaly . I will give this a try.

**Comment by annjawn** [comment]
Alright, I am back to using `serverless-mysql` with `await mysql.end()` although I am not sure if i'd be able to re-create the issue again. I will report back if this happens but thanks for the help!

**Comment by annjawn** [comment]
Alright, so I tried with `await mysql.end()` but I am noticing a weird behavior. When I am using `await` many session threads aren't actually ending (some are). I can see the processlist piling up with `sleep` sessions with `cleaned up` State. `cleaned up` according to AWS means that the client has not closed the connections as per the response in [this thread](https://forums.aws.amazon.com/thread.jspa?messageID=708499). 

I have a watchdog timer function that keeps track of each of the lambda functions execution time and returns back an error object (back to API gateway)1 second  before the lambda times out. This was created so that my APIs respond back to the client with appropriate error code in case of a timeout such that it can be handled appropriately. The timer function looks like this

```
function setupWatchdogTimer(context) {
    // When timer triggers, emit an event to the 'myErrorHandler' function
    
    const timeoutHandler = () => {
      // Include original event and request ID for diagnostics
      console.log("Error:" + context.functionName + " Function timed out...");
      return {code: "400", message: "Cannot perform action at this time, the server did not respond."};
    };
  
    // Set timer so it triggers one second before this function would timeout
    setTimeout(timeoutHandler, context.getRemainingTimeInMillis() - 1000);
  }
```

and it is called as `setupWatchdogTimer(context);` in the beginning of the Lambda execution inside of `exports.handler = async (event, context) => { ... }`. Now with `await mysql.end()` I am noticing " Function timed out..." message in Cloudwatch log much frequently, and those are the same invocations where the RDS instance keeps a lingering process in `sleep` and `cleaned up` State. Once I changed to just `mysql.end()`, my Lmabdas are not timing out anymore & I am noticing much less `sleep` processes piling up. Although I have not been able to re-create my original issue, I am worried that too many sleep sessions may cause the server the start refusing connections at scale. I will be switching back to using just `mysql.end()` without the `await` for now and see how it goes.

**Comment by jeremydaly** [comment]
@annjawn The purpose of serverless-mysql is to maintain a ratio of persistent connections so that your serverless functions will smartly reuse them when necessary, and clean them up when server resources are running low. 

`await mysql.end()` is what allows serverless-mysql to run the process to clean up those connections. If you don’t `await` that call, then the connection is frozen before it can do its job.

If you want to minimize the number of sleeping connections, set the `connUtilization` configuration option to something lower than the default of 0.8 (which will keep 80% of your maxConnections open). Set it to something like 0.5, or you can set a max user connections on your server and connect to MySQL with that.

**Comment by annjawn** [comment]
@jeremydaly I actually did hit that issue again this morning, so it's safe to say that `await` was actually the right way to do it. Putting back `await` resolved it and I can confirm that now. As for the `sleep` sessions, it's not a big deal since the number of active users on our app is going to be very small, so I am not too worried about it.

Sheesh! talk about session handling on serverless apps.... thanks a bunch for the help so far.

**Comment by SebSchwartz** [comment]
I still got this error from time to time :/
Before this error, I got this one: 
```javascript
{
    "errorMessage": "Connection lost: The server closed the connection.",
    "errorType": "Error",
    "stackTrace": [
        "Protocol.end (/var/task/node_modules/mysql/lib/protocol/Protocol.js:112:13)",
        "Socket.<anonymous> (/var/task/node_modules/mysql/lib/Connection.js:97:28)",
        "Socket.<anonymous> (/var/task/node_modules/mysql/lib/Connection.js:502:10)",
        "emitNone (events.js:111:20)",
        "Socket.emit (events.js:208:7)",
        "endReadableNT (_stream_readable.js:1064:12)",
        "_combinedTickCallback (internal/process/next_tick.js:138:11)",
        "process._tickDomainCallback (internal/process/next_tick.js:218:9)",
        "    --------------------",
        "Protocol._enqueue (/var/task/node_modules/mysql/lib/protocol/Protocol.js:144:48)",
        "Connection.query (/var/task/node_modules/mysql/lib/Connection.js:200:25)",
        "Promise (/var/task/node_modules/serverless-mysql/index.js:185:23)",
        "new Promise (<anonymous>)",
        "Object.query (/var/task/node_modules/serverless-mysql/index.js:183:10)",
        "<anonymous>"
    ]
}
```

The DB server is Aurora Serverless. And this fail after some queries are done. I'll try to gather more informations the next time I hit this error.

**Comment by annjawn** [comment]
@SebSchwartz you can use but I don't believe you need this library for Aurora Serverless since Lambda and Aurora would do the connection management for you in that case. Atleast that is what I think but @jeremydaly can confirm. Plus, there are some limitations to Aurora MySQL Serverless as of right now so perhaps review those.

**Comment by jeremydaly** [comment]
@SebSchwartz @annjawn Aurora Serverless does not handle connection management for you. It just scales up ACUs (Aurora Compute Units) as memory and connection requirements increase. It will not manage disconnecting zombie connections like this library does.

**Comment by jeremydaly** [comment]
@SebSchwartz If you could add some additional context to this, that would be great. I'm also waiting to see what happens at re:Invent. If we get RDS HTTP endpoints, then this library may become moot.

**Comment by SebSchwartz** [comment]
So in the current logs I got no more info than lots of connection lost before this error happens. I suppose the connection lost could be related to aurora or the library if a connection is closed but still used.
To give you more context, my application is using appsync (graphql) with lambda resolver which query the database. So what's happening is that if I'm querying a type with lots of subtypes to resolve, I can have more or less 800 lambdas working at the same time. They are executing simple and fast query and all calling the .end() method when they are done (only one lambda run's in parallel for all calls).
I checked the aurora connections and the maximum I got is 68 connections for 2ACU (max is 90). What can I log inside my lambda or which logs could be usefull to debug this?

Yes I hope they'll annonce big things for Aurora Serveless at re:Invent :)

**Comment by jeremydaly** [comment]
Looks like we don't have to wait until re:Invent: https://aws.amazon.com/about-aws/whats-new/2018/11/aurora-serverless-data-api-beta/

**Comment by SebSchwartz** [comment]
Great, I hope this will go out of beta soon or at least, be expanded to more regions 👍

**Comment by jeremydaly** [comment]
I still want to dig into this issue a bit more, but as I said, this library will be a bit of a moot point once HTTP RDS goes GA.

**Comment by SebSchwartz** [comment]
Yes as I said, if there is some usefull logs that I can add the the lambda to debug this, be my guest ;)

**Comment by annjawn** [comment]
@jeremydaly i faced the error again today when Amazon did the cluster changes to MySQL Aurora. The instance apparently came down and 1 particular Lambda function started giving this error below, which is the same as the one in my original post. To resolve this, I just saved the Lambda Function again which terminated any existing containers. The issue then went away. I think what's happening is the few persistent connections that Lambda is maintaining with MySQL suddenly gets broken as soon as the DB crashes/goes down. Any new requests that attempts to put a new query into the queue is then presented with the error below since the connection is maintained outside of the handler. Performing anything in the catch block with the `mysql` object at this point will persistently throw the same error as below.

Is the only way to fix this is by using `context.done()` or `process.exit()` to kill the container in the `catch` block, or is there some other way? or is there a way to re-establish a working connection with the same instance of the Lambda container? (**NOTE**: I am noticing that the Containers are remaining hot for as much as 20 to 40 minutes at a time)

```
Error: { Error: Cannot enqueue Query after fatal error.
at Protocol._validateEnqueue (/var/task/node_modules/mysql/lib/protocol/Protocol.js:200:16)
at Protocol._enqueue (/var/task/node_modules/mysql/lib/protocol/Protocol.js:138:13)
at Connection.query (/var/task/node_modules/mysql/lib/Connection.js:200:25)
at Promise (/var/task/node_modules/serverless-mysql/index.js:185:23)
at new Promise (<anonymous>)
at Object.query (/var/task/node_modules/serverless-mysql/index.js:183:10)
at <anonymous> code: 'PROTOCOL_ENQUEUE_AFTER_FATAL_ERROR', fatal: false }
```

**Comment by annjawn** [comment]
I see a fix was released for this. Will test it out today. Thanks Jeremy.

**Comment by SebSchwartz** [comment]
Great, I tested it and it seems to fix the issue ;)
I didn't get the error since I updated to last version.

Thanks for the fix @jeremydaly !

**Comment by jeremydaly** [comment]
Awesome, @SebSchwartz! Thanks for testing!

**Comment by annjawn** [comment]
I can confirm that it worked too. Thanks a lot.
