### ISSUE TITLE
Node 10 and 12 compatible?

### ISSUE THREAD

**Issue by JenningsCapgemini** [jeremydaly/serverless-mysql#75]
thanks

**Comment by cbschuld** [comment]
@JenningsCapgemini - I am using it on Node 12 and 14 and it works fine.  I have not tried it on 10 but I would suggest it's compatible.

**Comment by jeremydaly** [comment]
Sorry for the late reply. This was originally built for Node 8, so yes, 10 and 12 are compatible.
