### ISSUE TITLE
Multi-tenant Ability

### ISSUE THREAD

**Issue by wasitim** [jeremydaly/serverless-mysql#8]
I have a scenario where users come from different organizations and each organization has it's own replica of the db. Is there a way to maintain of cache of connections in the global space so my lambda can grab the connect one?

**Comment by jeremydaly** [comment]
The connection reference is saved in a variable, so you could create an object with multiple references and then pick the appropriate one. Would that work?

**Comment by wasitim** [comment]
Yup, that's the path I went down. Seemed a bit too simple.
