### ISSUE TITLE
RDS Proxy

### ISSUE THREAD

**Issue by ghost** [jeremydaly/serverless-mysql#81]
@jeremydaly what's your approach towards RDS Proxy (https://aws.amazon.com/rds/proxy/)? Would you consider using both serverless MySQL and Proxy together or is that an overkill (as they kinda overlap in connection clean up functionality)

**Comment by stephanelpaul** [comment]
if your using aurora serverless mysql don't need the proxy, if your using aurora mysql or rds mysql yes use a proxy for serverless apps.

**Comment by trademark18** [comment]
To be clear, it's not possible to use RDS Proxy with Aurora Serverless, per [AWS docs](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/rds-proxy.html#rds-proxy.limits): 

> You can't use RDS Proxy with Aurora Serverless clusters.

**Comment by Markkos89** [comment]
@Morindal do you use RDS? how did you solved your issue? facing something simillar here.

As per @StephaneP says, you should use the RDS Proxy with RDS + serverless-mysql, BUT, as far as I understood, the question was more like wich of the following approaches/options to use:

option 1 would be: RDS + RDS Proxy + serverless-mysql as the best approach. (we **need** the proxy) or, option 2, that would be RDS + serverless-mysql (as it already cleans up the connection) wich is already enough and it's also a good approach too.

I'm starting using serverless-mysql and I'm having same doubts, wich option is best?

thanks advance in case one of you replies!

**Comment by shmuel-torii** [comment]
@Markkos89 What are the conclusions? Are you using serverless-mysql in conjunction with RDS-Proxy?

**Comment by Markkos89** [comment]
> @Markkos89 What are the conclusions? Are you using serverless-mysql in conjunction with RDS-Proxy?

Hi there! In my case instead of using RDS, we moved to DynamoDB :sunglasses:

**Comment by naorpeled** [comment]
Afaik when using an RDS proxy there's no need in using serverless-mysql,
the proxy handles all the zombie connections logic.
