### ISSUE TITLE
Pick DB Host based on environment

### ISSUE THREAD

**Issue by aj0y** [jeremydaly/serverless-mysql#84]
I have multiple "environments" setup for Lambda. One for staging and one for production etc. The DB host is different for each environment.
If the mysql configuration needs to be outside the lambda handler, how can i inform it about the environment it's being invoked in? and subsequently the host/db configuration to use? 

The environment is usually passed through the context parameter in the aws handler code.
Any ideas on how to solve that?

**Comment by aj0y** [comment]
I guess the solution is to run the configuration code inside the handler?

**Comment by stephanelpaul** [comment]
if your using lambda#edge use ssm, if your using lambda you can use env variables.

**Comment by Markkos89** [comment]
@aj0y have you solved it? facing simillar issue here

**Comment by naorpeled** [comment]
Hey @aj0y,
thanks for opening this issue!

You should take a look at [this comment](https://github.com/jeremydaly/serverless-mysql/issues/129#issuecomment-1126689866).

It contains a snippet that can help you achieve exactly what you're looking for.
