### ISSUE TITLE
Cannot read property 'rollback' of undefined at Query.client.query (index.js:191:20)

### ISSUE THREAD

**Issue by domingguss** [jeremydaly/serverless-mysql#9]
we sometimes encounter this:

```
START RequestId: 0cf8d5a3-ddc5-11e8-8e93-49a30debc796 Version: $LATEST

UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'rollback' of undefined at Query.client.query (/var/task/node_modules/serverless-mysql/index.js:191:20) at Query.<anonymous> (/var/task/node_modules/mysql/lib/Connection.js:502:10) at Query._callback (/var/task/node_modules/mysql/lib/Connection.js:468
2018-11-01T10:58:23.191Z 8780e583-ddc4-11e8-9428-fd83c489432e (node:1) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'rollback' of undefined
at Query.client.query (/var/task/node_modules/serverless-mysql/index.js:191:20)
at Query.<anonymous> (/var/task/node_modules/mysql/lib/Connection.js:502:10)
at Query._callback (/var/task/node_modules/mysql/lib/Connection.js:468:16)
at Query.Sequence.end (/var/task/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
at /var/task/node_modules/mysql/lib/protocol/Protocol.js:396:18
at Array.forEach (<anonymous>)
at /var/task/node_modules/mysql/lib/protocol/Protocol.js:395:13
at _combinedTickCallback (internal/process/next_tick.js:131:7)
at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

This suggests that `this` on that line is undefined... how's that even possible? 🤔

this happens in AWS, and we use Serverless (with split stacks) to create ± 60 different api endpoints on API Gateway.

We initialize serverless-mysql properly (outside main handler), and every handler awaits `mysql.end()`. It's as if the client is still discarded over time. (maybe after the zombie period sleeping?) 

edit:
After reading the code in the library, could it be that it maybe is killing zombies too easily? Or that it kills connections from other 'sleeping' lambda functions which it shouldn't?

**Comment by domingguss** [comment]
I also sometimes encounter this, upon 'resuming' a sleeping database connection, so when a lambda is called within the timelimits..

```
START RequestId: 0cf8d5a3-ddc5-11e8-8e93-49a30debc796 Version: $LATEST

UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'rollback' of undefined at Query.client.query (/var/task/node_modules/serverless-mysql/index.js:191:20) at Query.<anonymous> (/var/task/node_modules/mysql/lib/Connection.js:502:10) at Query._callback (/var/task/node_modules/mysql/lib/Connection.js:468
2018-11-01T10:58:23.191Z 8780e583-ddc4-11e8-9428-fd83c489432e (node:1) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'rollback' of undefined
at Query.client.query (/var/task/node_modules/serverless-mysql/index.js:191:20)
at Query.<anonymous> (/var/task/node_modules/mysql/lib/Connection.js:502:10)
at Query._callback (/var/task/node_modules/mysql/lib/Connection.js:468:16)
at Query.Sequence.end (/var/task/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
at /var/task/node_modules/mysql/lib/protocol/Protocol.js:396:18
at Array.forEach (<anonymous>)
at /var/task/node_modules/mysql/lib/protocol/Protocol.js:395:13
at _combinedTickCallback (internal/process/next_tick.js:131:7)
at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

This suggests that `this` on that line is undefined... how's that even possible? 🤔

**Comment by domingguss** [comment]
i have forked the repo and added a console.log to log the error:
```
{
    "code": "ER_NO_SUCH_THREAD",
    "errno": 1094,
    "sqlMessage": "Unknown thread id: 26979",
    "sqlState": "HY000",
    "index": 0,
    "sql": "KILL 26979"
}
```

**Comment by jeremydaly** [comment]
@domingguss, thanks for reporting this. I see you submitted a PR, but I need to study the issue a bit more.

**Comment by domingguss** [comment]
I found that you sometimes pass the rollback as context, but not always, thats why a `this` null check is needed  - `if (this && this.rollback) {`

But after adding that null-check, I still found out it still returns unhandled Promises, so I dug deeper.
What I eventually did to fix this issue, was loosen the condition when to destroy the client (to also kill client on connection lost), and re-ordered some lines. I also added a `return` before `reject(err)`, for symetrical's sake. 
Pardon me for the many commits on my fork - I had to deploy to AWS every time for proper testing...


What I did:
i tested with 
```
  zombieMinTimeout: 5,
  zombieMaxTimeout: 30,
```
and used two different lambda functions: 1 to test, and after 30 seconds I invoke a different lambda function( > zombie timeout) to kill the first one's sleeping connection.  
After that, when invoking the first lamba function, I logged these errors:
`{"fatal":true,"code":"PROTOCOL_CONNECTION_LOST"} `
because I already added a `this` null check, this didn't fail anymore (.rollback is undefined).
Subsequently after this one, I see these in the logs:
`{"code":"PROTOCOL_ENQUEUE_AFTER_FATAL_ERROR","fatal":false}`
`UnhandledPromiseRejectionWarning: Error: Cannot enqueue Query after fatal error.`

Every time I envoke this lambda function, I get these errors...
This eventually lead to a live client with a dead connection without a proper way to create a new connection. So to fix this, I weakened the if statement to destroy the client with `|| tooManyConnsErrors.includes(err.code)` - and it now seems to work..

Feel free to investigate further - I hope this helps though!

**Comment by domingguss** [comment]
now that I think about it, when encountering `PROTOCOL_CONNECTION_LOST`, it would be better to  recreate the client and try the query again, instead of returning an error... but that might be more complicated in that `.apply` function...

**Comment by JakubMatejka** [comment]
Any news on this? I deployed this module to our app today and we've got first such error only few hours later. ;o( We configure just the db connection, nothing special (https://github.com/keboola/developer-portal/blob/master/src/lib/services.js#L31-L40)

**Comment by dortheimer** [comment]
I've got this error also and it's a pain.

**Comment by domingguss** [comment]
might consider implementing https://aws.amazon.com/about-aws/whats-new/2018/11/aurora-serverless-data-api-beta/ which @jeremydaly already mentioned in another issue :)

**Comment by jeremydaly** [comment]
Hi everyone! I had heard whispers of the Data API, so I was waiting to see if it would render this library moot. I don’t think that is the case, at least not for awhile. So, when I get back from re:Invent next week, I’ll fix these issues.

**Comment by jeremydaly** [comment]
@domingguss, can you try to replicate the issue with v1.2.0? I'm not sure we need the connection handling, and since I added the ENQUEUE checks, it should reset the connect and retry the query if need be.

Thanks again for the feedback and the pull request.
