### ISSUE TITLE
Strategies for dealing with cold starts

### ISSUE THREAD

**Issue by MarkOnDuty** [jeremydaly/serverless-mysql#90]
First, this project is a life saver. Thanks Jeremy!

We are using Aurora Serverless via Serverless MySQL and are noticing that the cold start time for a database can be more than ten seconds, sometimes a lot more, more than the 29-second hard limit for API Gateway, compared to no more than 10 seconds for a Lambda cold start. We are wondering about strategies for getting appropriate messaging back to the client letting them know that the connection is being opened.

Just hoping to start a discussion about strategies for dealing with this sort of situation. Here are some things we've thought about:

1. Keeping the database warm is one option, but not possible for many scenarios.
2. Inferring that a cold start has happened by the time period between request and response.
3. SQS or SNS might be an option, maybe as a separate channel for communicating lambda progress, or as a way of decoupling requests from responses.
4. What we really want is a way to test whether the DB is starting cold, immediately send a reply through API Gateway (ie. "warming up, try again in 10s"), continue to bring the connection up, then exit.

Options 1, 2, and 3 all seem possible, but I can't say the same about 4. Serverless MySQL's events make it easy to track the database's state in a lambda, but API Gateway seems to demand that processing finish when a reply is sent.

Any suggestions?

**Comment by map1336** [comment]
@MarkOnDuty Hi, maybe this will be a interesting note for you or a posibble recommendation:
Mentioned by @jeremydaly which i totally agree with

- In production mode: Do not allow the serverless aurora instance get to 0 ACU ( I mean turn off)
It could make your clients have a bad time! 
And somehow your Lambda's bills could be more expensive.

- If you already know the possible workload your database will be getting, i recommend you using an Aurora Instance (Non-serverless with RDS Proxy), it could be an effective solution and cheaper!

**Comment by MarkOnDuty** [comment]
@isaacp0310, thanks for the response. Those are options for workloads that justify the expense of dedicated resources. But lets you say that your system is used unpredictably, with gaps of days between use. When it is used, it is hammered for about an hour.

What we are looking for is a way to let the client know that things are warming up, so that they don't get frustrated and take off.

Can we query the state of the database from the client? That would do the trick. We would just check the state before making a query?

Abandoning the request-response model altogether would be best.

> @MarkOnDuty Hi, maybe this will be a interesting note for you or a posibble recommendation:
> Mentioned by @jeremydaly which i totally agree with
> 
> * In production mode: Do not allow the serverless aurora instance get to 0 ACU ( I mean turn off)
>   It could make your clients have a bad time!
>   And somehow your Lambda's bills could be more expensive.
> * If you already know the possible workload your database will be getting, i recommend you using an Aurora Instance (Non-serverless with RDS Proxy), it could be an effective solution and cheaper!

**Comment by MarkOnDuty** [comment]
So here's some interesting ideas related to this, and from @jeremydaly too:

1. https://www.jeremydaly.com/the-storage-first-pattern/
2. https://www.jeremydaly.com/the-circuit-breaker/

The storage first pattern could work, but we would need some way of checking that the request succeeded eventually. That isn't too hard.

The circuit-breaker pattern is almost exactly what we want. All it needs to cover the cold-start scenario is a way to let the client know that the DB is cold, but proceed to warm up the DB after sending the client the cold start message.

**Comment by Markkos89** [comment]
Hi @ipr0310 @MarkOnDuty, just stteped with this excelent package and reading about it. Excuse me if this _late_ reply bothers some of you, but have you solved your issue? I would appreciate if some of you could share the solution implemented in such case.

Another thing, related to cold starts, have some of you saw [this Jeremy's article](https://www.jeremydaly.com/solving-cold-start-problem/)? 
A few months later, he wrote  [another article](https://www.jeremydaly.com/lambda-warmer-optimize-aws-lambda-function-cold-starts/) with a proper solution and made a new npm package, called [lambda-warmer](https://www.npmjs.com/package/lambda-warmer/v/1.2.2), that solves cold starts issues and it might help you solve your problems if it's related to that.

Hoping the links helps somebody.

Best regards!
