### ISSUE TITLE
Can't execute query

### ISSUE THREAD

**Issue by carlosfer02** [jeremydaly/serverless-mysql#97]
I am using serverless Lambda and for some reason i am not able to execute any query, here is my code:

```
const mysql = require('serverless-mysql')({
    config: {
        host     : process.env.HOST_DB,
        database : process.env.DATABASE_DB,
        user     : process.env.USER_DB,
        password : process.env.PASS_DB
    }
});

module.exports.index = async (event) => {
    const token = event.headers.Authorization;
    const values = session.verifyToken(token);

    console.log('start'); <--- It gets here
    try {
        var results = await mysql.query('SELECT * FROM clients WHERE id=1'); <--- It can not pass through here
        console.log(results);
    } catch (e) {
        console.log(e);
    }
```

I get the next error from cloud watch:
`ERROR   Invoke Error    {"errorType":"TypeError","errorMessage":"mysql.connect is not a function","stack":["TypeError: mysql.connect is not a function","    at Runtime.module.exports.index [as handler] (/var/task/functions/panel.js:9:17)","    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)"]}`

Am i doing something wrong?

**Comment by jeremydaly** [comment]
Did you figure this out?
